### ISSUE TITLE
Using the code?

### ISSUE THREAD

**Issue by meshula** [raph080/ImGuiHydraEditor#2]
Hi @raph080! Would you mind if I use your outliner in my own project? It's very nice. My project is BSD licensed, but I'm not spotting one here, so I thought I'd ask permission :)

**Comment by raph080** [comment]
Hi Nick, thank you very much for your feedback. I indeed forgot to specify the license. You will now find the MIT license in my repos.
Do not hesitate to tag my project in yours as source or other :)

Raphael

**Comment by meshula** [comment]
Thanks :)

**Comment by meshula** [comment]
While, I'm here, I'll also mention I like how you set up TextEditor as well! Your project is very inspiring.
